### PR TITLE
A fairly big amount of small improvements

### LINKED ISSUE #98: `Minified React error #31` on /jobs/:id
I'm getting the following error on `#/jobs/insights-worker`

```
Error: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]…0keys%20%7Bbownty.scale.queue_name%2C%20bownty.scale.use_config%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (http://localhost:8001/main.120138a39287c886fd52.js:2:17241)
    at a (http://localhost:8001/main.120138a39287c886fd52.js:5:6977)
    at o (http://localhost:8001/main.120138a39287c886fd52.js:5:7107)
    at Object.instantiateChildren (http://localhost:8001/main.120138a39287c886fd52.js:20:15334)
    at p._reconcilerInstantiateChildren (http://localhost:8001/main.120138a39287c886fd52.js:21:18816)
    at p.mountChildren (http://localhost:8001/main.120138a39287c886fd52.js:21:19023)
    at p._createInitialChildren (http://localhost:8001/main.120138a39287c886fd52.js:20:31912)
    at p.mountComponent (http://localhost:8001/main.120138a39287c886fd52.js:20:30064)
    at Object.mountComponent (http://localhost:8001/main.120138a39287c886fd52.js:3:19006)
    at p.mountChildren (http://localhost:8001/main.120138a39287c886fd52.js:21:19157)
```

My job file (json)

```json
{
  "Region": "global",
  "ID": "insights-worker",
  "ParentID": "",
  "Name": "insights-worker",
  "Type": "service",
  "Priority": 50,
  "AllAtOnce": false,
  "Datacenters": [
    "production",
    "vagrant"
  ],
  "Constraints": [
    {
      "LTarget": "${meta.worker}",
      "RTarget": "1",
      "Operand": "="
    }
  ],
  "TaskGroups": [
    {
      "Name": "alert-server",
      "Count": 0,
      "Constraints": null,
      "RestartPolicy": {
        "Attempts": 2,
        "Interval": 60000000000,
        "Delay": 15000000000,
        "Mode": "delay"
      },
      "Tasks": [
        {
          "Name": "server",
          "Driver": "raw_exec",
          "User": "",
          "Config": {
            "command": "/usr/local/bin/envconsul",
            "args": [
              "-config /etc/envconsul/config.hcl -prefix apps/insights/nomad/alert-server/server/env -prefix apps/insights/env -wait 3s:6s -splay 3s -sanitize -upcase /opt/deploy/www/insights/htdocs/app/bin/cake alert server"
            ]
          },
          "Env": {
            "APP_VERSION": "1475",
            "APP_ENV": "production"
          },
          "Services": null,
          "Constraints": null,
          "Resources": {
            "CPU": 500,
            "MemoryMB": 128,
            "DiskMB": 300,
            "IOPS": 0,
            "Networks": null
          },
          "Meta": {
            "bownty.exec.command": "/opt/deploy/www/insights/htdocs/app/bin/cake alert server"
          },
          "KillTimeout": 5000000000,
          "LogConfig": {
            "MaxFiles": 10,
            "MaxFileSizeMB": 10
          },
          "Artifacts": null
        }
      ],
      "Meta": {
        "bownty.scale.use_config": "default",
        "bownty.scale.queue_name": "insights.alert_checks"
      }
    },
    {
      "Name": "click-rollup",
      "Count": 1,
      "Constraints": null,
      "RestartPolicy": {
        "Attempts": 2,
        "Interval": 60000000000,
        "Delay": 15000000000,
        "Mode": "delay"
      },
      "Tasks": [
        {
          "Name": "server",
          "Driver": "raw_exec",
          "User": "",
          "Config": {
            "command": "/usr/local/bin/envconsul",
            "args": [
              "-config /etc/envconsul/config.hcl -prefix apps/insights/nomad/click-rollup/server/env -prefix apps/insights/env -wait 3s:6s -splay 3s -sanitize -upcase /opt/deploy/www/insights/htdocs/app/bin/cake click_rollup server"
            ]
          },
          "Env": {
            "APP_VERSION": "1475",
            "APP_ENV": "production"
          },
          "Services": null,
          "Constraints": null,
          "Resources": {
            "CPU": 500,
            "MemoryMB": 128,
            "DiskMB": 300,
            "IOPS": 0,
            "Networks": null
          },
          "Meta": {
            "bownty.exec.command": "/opt/deploy/www/insights/htdocs/app/bin/cake click_rollup server"
          },
          "KillTimeout": 5000000000,
          "LogConfig": {
            "MaxFiles": 10,
            "MaxFileSizeMB": 10
          },
          "Artifacts": null
        }
      ],
      "Meta": {
        "bownty.scale.queue_name": "insights.click_rollup",
        "bownty.scale.use_config": "default"
      }
    },
    {
      "Name": "cost-rollup",
      "Count": 0,
      "Constraints": null,
      "RestartPolicy": {
        "Attempts": 2,
        "Interval": 60000000000,
        "Delay": 15000000000,
        "Mode": "delay"
      },
      "Tasks": [
        {
          "Name": "server",
          "Driver": "raw_exec",
          "User": "",
          "Config": {
            "command": "/usr/local/bin/envconsul",
            "args": [
              "-config /etc/envconsul/config.hcl -prefix apps/insights/nomad/cost-rollup/server/env -prefix apps/insights/env -wait 3s:6s -splay 3s -sanitize -upcase /opt/deploy/www/insights/htdocs/app/bin/cake campaign_cost server"
            ]
          },
          "Env": {
            "APP_ENV": "production",
            "APP_VERSION": "1475"
          },
          "Services": null,
          "Constraints": null,
          "Resources": {
            "CPU": 500,
            "MemoryMB": 128,
            "DiskMB": 300,
            "IOPS": 0,
            "Networks": null
          },
          "Meta": {
            "bownty.exec.command": "/opt/deploy/www/insights/htdocs/app/bin/cake campaign_cost server"
          },
          "KillTimeout": 5000000000,
          "LogConfig": {
            "MaxFiles": 10,
            "MaxFileSizeMB": 10
          },
          "Artifacts": null
        }
      ],
      "Meta": {
        "bownty.scale.queue_name": "insights.cost_rollups",
        "bownty.scale.use_config": "default"
      }
    },
    {
      "Name": "campaign-attribution-fixer",
      "Count": 0,
      "Constraints": null,
      "RestartPolicy": {
        "Attempts": 2,
        "Interval": 60000000000,
        "Delay": 15000000000,
        "Mode": "delay"
      },
      "Tasks": [
        {
          "Name": "server",
          "Driver": "raw_exec",
          "User": "",
          "Config": {
            "command": "/usr/local/bin/envconsul",
            "args": [
              "-config /etc/envconsul/config.hcl -prefix apps/insights/nomad/campaign-attribution-fixer/server/env -prefix apps/insights/env -wait 3s:6s -splay 3s -sanitize -upcase /opt/deploy/www/insights/htdocs/app/bin/cake campaign_attribution server"
            ]
          },
          "Env": {
            "APP_ENV": "production",
            "APP_VERSION": "1475"
          },
          "Services": null,
          "Constraints": null,
          "Resources": {
            "CPU": 500,
            "MemoryMB": 128,
            "DiskMB": 300,
            "IOPS": 0,
            "Networks": null
          },
          "Meta": {
            "bownty.exec.command": "/opt/deploy/www/insights/htdocs/app/bin/cake campaign_attribution server"
          },
          "KillTimeout": 5000000000,
          "LogConfig": {
            "MaxFiles": 10,
            "MaxFileSizeMB": 10
          },
          "Artifacts": null
        }
      ],
      "Meta": {
        "bownty.scale.queue_name": "insights.campaign_attribution_fix",
        "bownty.scale.use_config": "default"
      }
    },
    {
      "Name": "cassandra-copy-server",
      "Count": 0,
      "Constraints": null,
      "RestartPolicy": {
        "Attempts": 2,
        "Interval": 60000000000,
        "Delay": 15000000000,
        "Mode": "delay"
      },
      "Tasks": [
        {
          "Name": "server",
          "Driver": "raw_exec",
          "User": "",
          "Config": {
            "command": "/usr/local/bin/envconsul",
            "args": [
              "-config /etc/envconsul/config.hcl -prefix apps/insights/nomad/cassandra-copy-server/server/env -prefix apps/insights/env -wait 3s:6s -splay 3s -sanitize -upcase /opt/deploy/www/insights/htdocs/app/bin/cake cassandra_newsletter copy_server"
            ]
          },
          "Env": {
            "APP_VERSION": "1475",
            "APP_ENV": "production"
          },
          "Services": null,
          "Constraints": null,
          "Resources": {
            "CPU": 500,
            "MemoryMB": 128,
            "DiskMB": 300,
            "IOPS": 0,
            "Networks": null
          },
          "Meta": {
            "bownty.exec.command": "/opt/deploy/www/insights/htdocs/app/bin/cake cassandra_newsletter copy_server"
          },
          "KillTimeout": 5000000000,
          "LogConfig": {
            "MaxFiles": 10,
            "MaxFileSizeMB": 10
          },
          "Artifacts": null
        }
      ],
      "Meta": {
        "bownty.scale.queue_name": "cassandra_newsletter.copy",
        "bownty.scale.use_config": "default"
      }
    },
    {
      "Name": "cassandra-compare-server",
      "Count": 0,
      "Constraints": null,
      "RestartPolicy": {
        "Attempts": 2,
        "Interval": 60000000000,
        "Delay": 15000000000,
        "Mode": "delay"
      },
      "Tasks": [
        {
          "Name": "server",
          "Driver": "raw_exec",
          "User": "",
          "Config": {
            "args": [
              "-config /etc/envconsul/config.hcl -prefix apps/insights/nomad/cassandra-compare-server/server/env -prefix apps/insights/env -wait 3s:6s -splay 3s -sanitize -upcase /opt/deploy/www/insights/htdocs/app/bin/cake cassandra_newsletter compare_server"
            ],
            "command": "/usr/local/bin/envconsul"
          },
          "Env": {
            "APP_VERSION": "1475",
            "APP_ENV": "production"
          },
          "Services": null,
          "Constraints": null,
          "Resources": {
            "CPU": 500,
            "MemoryMB": 128,
            "DiskMB": 300,
            "IOPS": 0,
            "Networks": null
          },
          "Meta": {
            "bownty.exec.command": "/opt/deploy/www/insights/htdocs/app/bin/cake cassandra_newsletter compare_server"
          },
          "KillTimeout": 5000000000,
          "LogConfig": {
            "MaxFiles": 10,
            "MaxFileSizeMB": 10
          },
          "Artifacts": null
        }
      ],
      "Meta": {
        "bownty.scale.use_config": "default",
        "bownty.scale.queue_name": "cassandra_newsletter.compare"
      }
    },
    {
      "Name": "cassandra-move-server",
      "Count": 0,
      "Constraints": null,
      "RestartPolicy": {
        "Attempts": 2,
        "Interval": 60000000000,
        "Delay": 15000000000,
        "Mode": "delay"
      },
      "Tasks": [
        {
          "Name": "server",
          "Driver": "raw_exec",
          "User": "",
          "Config": {
            "command": "/usr/local/bin/envconsul",
            "args": [
              "-config /etc/envconsul/config.hcl -prefix apps/insights/nomad/cassandra-move-server/server/env -prefix apps/insights/env -wait 3s:6s -splay 3s -sanitize -upcase /opt/deploy/www/insights/htdocs/app/bin/cake cassandra_newsletter move_server"
            ]
          },
          "Env": {
            "APP_ENV": "production",
            "APP_VERSION": "1475"
          },
          "Services": null,
          "Constraints": null,
          "Resources": {
            "CPU": 500,
            "MemoryMB": 128,
            "DiskMB": 300,
            "IOPS": 0,
            "Networks": null
          },
          "Meta": {
            "bownty.exec.command": "/opt/deploy/www/insights/htdocs/app/bin/cake cassandra_newsletter move_server"
          },
          "KillTimeout": 5000000000,
          "LogConfig": {
            "MaxFiles": 10,
            "MaxFileSizeMB": 10
          },
          "Artifacts": null
        }
      ],
      "Meta": {
        "bownty.scale.queue_name": "cassandra_newsletter.move",
        "bownty.scale.use_config": "default"
      }
    },
    {
      "Name": "cassandra-delete-server",
      "Count": 0,
      "Constraints": null,
      "RestartPolicy": {
        "Attempts": 2,
        "Interval": 60000000000,
        "Delay": 15000000000,
        "Mode": "delay"
      },
      "Tasks": [
        {
          "Name": "server",
          "Driver": "raw_exec",
          "User": "",
          "Config": {
            "args": [
              "-config /etc/envconsul/config.hcl -prefix apps/insights/nomad/cassandra-delete-server/server/env -prefix apps/insights/env -wait 3s:6s -splay 3s -sanitize -upcase /opt/deploy/www/insights/htdocs/app/bin/cake cassandra_newsletter delete_server"
            ],
            "command": "/usr/local/bin/envconsul"
          },
          "Env": {
            "APP_ENV": "production",
            "APP_VERSION": "1475"
          },
          "Services": null,
          "Constraints": null,
          "Resources": {
            "CPU": 500,
            "MemoryMB": 128,
            "DiskMB": 300,
            "IOPS": 0,
            "Networks": null
          },
          "Meta": {
            "bownty.exec.command": "/opt/deploy/www/insights/htdocs/app/bin/cake cassandra_newsletter delete_server"
          },
          "KillTimeout": 5000000000,
          "LogConfig": {
            "MaxFiles": 10,
            "MaxFileSizeMB": 10
          },
          "Artifacts": null
        }
      ],
      "Meta": {
        "bownty.scale.queue_name": "cassandra_newsletter.delete",
        "bownty.scale.use_config": "default"
      }
    }
  ],
  "Update": {
    "Stagger": 5000000000,
    "MaxParallel": 2
  },
  "Periodic": null,
  "Meta": {
    "bownty.scale_config.default.rule.1.comparison_value": "99",
    "bownty.env.APP_ENV": "production",
    "bownty.scale_config.default.rule.1.comparison": "above",
    "bownty.scale_config.default.rule.0.comparison_value": "90",
    "bownty.scale_config.default.rule.0.rule_type": "queue_efficiency",
    "bownty.scale_config.default.rule.1.rule_type": "queue_efficiency",
    "bownty.scale_config.default.min_processes": "0",
    "bownty.scale_config.default.max_processes": "6",
    "bownty.scale_config.default.rule.1.if_true": "decr_numprocs = 1",
    "bownty.scale_config.default.rule.0.comparison": "below",
    "bownty.env.APP_VERSION": "1475",
    "bownty.scale_config.default.rule.0.if_true": "incr_numprocs = 1"
  },
  "Status": "running",
  "StatusDescription": "",
  "CreateIndex": 544329,
  "ModifyIndex": 544645,
  "JobModifyIndex": 544645
}
```

### PR DESCRIPTION
**Pull request by jippi**
Should fix #98 

Also, I'm a terrible JS developer, can we please redo it in PHP ? :P

**update** I'm hotfixing various things I see as low-hanging fruits for our usage, feel free to discuss

**TODO**

- [ ] make `/jobs/:id/allocations` somehow show up in context of a job instead of on its own
- [ ] make `/jobs/:id/evaluations` somehow show up in context of a job instead of on its own

### CODE REVIEW

**Comment by jippi** [comment]
@iverberk i've think i've killed as many low-hanging fruits as i can by now :)

**Comment by iverberk** [comment]
Awesome, I'll take a look tonight! Many thanks for your efforts.

**Comment by jippi** [comment]
@iverberk some of the things may be too opinionated on how i currently work with nomad-ui :) e.g. changing the left-menu order of menus to match what's most important or not to me (or maybe any other operator)

File: frontend/src/components/job/info.js [hunk 1]
```diff
@@ -50,23 +54,30 @@ class JobInfo extends Component {
...
+                                            <dt>{jobProp}</dt>
+                                            <dd>{jobPropValue}</dd>
+                                        </div>
+                                    )
+                                }, this)}
+                            </dl>
+                        </div>
+                        <div className="col-lg-6 col-md-6 col-sm-12 col-sx-12">
+                            <legend>Meta Properties</legend>
+                            {this.collectMeta(this.props.job.Meta || {}, "wide")}
```
Comment (iverberk) [inline frontend/src/components/job/info.js]: Is the extra ```|| {}``` necessary? It's already checked in the function as well and I think .Meta is always there on the job object, although it may be empty.

File: frontend/src/containers/jobs.js [hunk 2]
```diff
@@ -3,6 +3,48 @@ import { connect } from 'react-redux';
 import { NomadLink } from '../components/link'
 
 class Jobs extends Component {
+
+    counterColumns() {
+        return ['Queued', 'Complete', 'Failed', 'Running', 'Starting', 'Lost'];
```
Comment (iverberk) [inline frontend/src/containers/jobs.js]: I would just make this a const in the file, outside of the class:
```
import ...

const summaryLabels = ['Queued', 'Complete', 'Failed', 'Running', 'Starting', 'Lost']

class Jobs extends Component {
```

File: frontend/src/components/link.js [hunk 3]
```diff
@@ -3,6 +3,16 @@ import { Link } from 'react-router';
 import shortUUID from '../helpers/uuid'
 
 export class NomadLink extends Component {
+
+    findNodeNameById(nodeId) {
+        let r = Object.keys(this.props.nodeList).filter(_ => { return this.props.nodeList[_]['ID'] === nodeId; })
```
Comment (iverberk) [inline frontend/src/components/link.js]: Just a nit, can we use 'const' instead of 'let' for immutable variables? Also, can we replace the underscore with a clear identifier like 'node'. That makes for more human-readable code.

File: frontend/src/containers/allocations.js [hunk 4]
```diff
@@ -33,7 +49,7 @@ class Allocations extends Component {
                                                 <td><NomadLink allocId={allocation.ID} short="true"/></td>
                                                 <td><NomadLink jobId={allocation.JobID} short="true"/></td>
                                                 <td>{allocation.ClientStatus}</td>
-                                                <td>{allocation.DesiredStatus}</td>
+                                                <td>{this.renderDesiredStatus(allocation)}</td>
```
Comment (iverberk) [inline frontend/src/containers/allocations.js]: This is really nice! I wonder if we should make it clear in the UI that more information is to be had by hovering over the item. What do you think?

File: frontend/assets/sass/nomad-ui.scss [hunk 5]
```diff
@@ -58,3 +58,11 @@
 .pointer {
 	cursor: pointer;
 }
+
+dl {
```
Comment (iverberk) [inline frontend/assets/sass/nomad-ui.scss]: I don't think this will be necessary if we remove the dd/dt lists from the tables?

File: frontend/src/components/sidebar.js [hunk 6]
```diff
@@ -11,37 +11,37 @@ const Sidebar = ({ location }) => {
                     </Link>
                 </div>
                 <ul className="nav">
-                    <li className={location.pathname === '/cluster' ? 'active' : ''}>
+                    <li className={location.pathname.indexOf('/cluster') === 0 ? 'active' : ''}>
```
Comment (iverberk) [inline frontend/src/components/sidebar.js]: I think we can use .startsWith('/cluster') for this. Makes things more obvious.

File: frontend/src/components/link.js (hunk 3 above)
Comment (jippi) [inline frontend/src/components/link.js]: I copied `_` from some other code in nomad-ui :P didn't even know it was possible until i saw it, i prefer a proper name ;)

File: frontend/src/containers/allocations.js (hunk 4 above)
Comment (jippi) [inline frontend/src/containers/allocations.js]: yeah, experimented with a small fa-icon next to it, but couldn't agree on something

considering a dotted underline might be a good solution now

File: frontend/src/components/sidebar.js (hunk 6 above)
Comment (jippi) [inline frontend/src/components/sidebar.js]: sure, didn't know that exist :P

File: frontend/src/components/job/info.js [hunk 7]
```diff
@@ -23,11 +23,23 @@ class JobInfo extends Component {
...
+            if (meta.length > 0) {
+                metaTag = <dl className="dl-horizontal">{meta}</dl>
+            }
+
             return (
                 <tr key={taskGroup.ID}>
                     <td>{taskGroup.Name}</td>
                     <td>{taskGroup.Count}</td>
-                    <td>{taskGroup.Meta || "<none>" }</td>
+                    <td>{metaTag}</td>
```
Comment (jippi) [inline frontend/src/components/job/info.js]: for me at least, my metadata is used to define auto-scale rules from my external system and other need-to-know information. Having this directly visible is important for me at least, not sure how other people use it. Personally I'm willing to sacrifice screen estate for more data directly visible. Would like to keep it in for now and see feedback on it.

A compromise could be long term to show number of tags as human readable, and abuse `tooltip` on hover to show the actual data :)

File: frontend/src/components/job/info.js (hunk 1 above)
Comment (jippi) [inline frontend/src/components/job/info.js]: Might be a refactor leftover :)

File: frontend/assets/sass/nomad-ui.scss (hunk 5 above)
Comment (jippi) [inline frontend/assets/sass/nomad-ui.scss]: it also slightly compress the job `dl` list :)

File: frontend/src/components/job/info.js (hunk 7 above)
Comment (iverberk) [inline frontend/src/components/job/info.js]: I'd be willing to sacrifice screen estate as well, but not in the table rows. I really think this makes for a bad UX when people have to put effort into determining where the row boundaries are. I think I would be okay with showing the number of meta tags and showing them while hovering. Let me think about it bit further.

File: frontend/src/containers/allocations.js (hunk 4 above)
Comment (iverberk) [inline frontend/src/containers/allocations.js]: dotted underline would be fine I think!

File: frontend/assets/sass/nomad-ui.scss (hunk 5 above)
Comment (iverberk) [inline frontend/assets/sass/nomad-ui.scss]: ok, we'll leave it in.

File: frontend/src/components/sidebar.js (hunk 6 above)
Comment (jippi) [inline frontend/src/components/sidebar.js]: Done

File: frontend/src/components/link.js (hunk 3 above)
Comment (jippi) [inline frontend/src/components/link.js]: Done

File: frontend/src/containers/jobs.js (hunk 2 above)
Comment (jippi) [inline frontend/src/containers/jobs.js]: Done

File: frontend/src/components/job/info.js (hunk 1 above)
Comment (jippi) [inline frontend/src/components/job/info.js]: Done

File: frontend/src/components/job/info.js (hunk 7 above)
Comment (jippi) [inline frontend/src/components/job/info.js]: I've added a more dense version which i really dig :) 

image

the keys show up as tooltip on hover :)

File: frontend/src/components/job/info.js [hunk 8]
```diff
@@ -13,7 +13,7 @@ class JobInfo extends Component {
              taskGroup.Tasks.map((task) => {
                 tasks.push(
                     <tr key={task.ID}>
-                        <td>{task.Name}</td>
+                        <td>{taskGroup.Name} / {task.Name}</td>
```
Comment (jippi) [inline frontend/src/components/job/info.js]: Done

File: frontend/src/components/job/info.js (hunk 7 above)
Comment (iverberk) [inline frontend/src/components/job/info.js]: I dig it as well, nice work!

File: frontend/src/components/job/allocs.js [hunk 9]
```diff
@@ -21,4 +21,9 @@ function mapStateToProps({ allocations, job, nodes }) {
 	return { allocations, job, nodes }
 }
 
+JobAllocs.defaultProps = {
```
Comment (iverberk) [inline frontend/src/components/job/allocs.js]: Why is this necessary? It's seems like a rather odd way to initialize variables. Can't we use the ES6 defaults for arguments?

File: frontend/src/components/charts/doughnut.js [hunk 10]
```diff
@@ -41,9 +47,10 @@ class Doughnut extends Component {
                     </div>
                     <div className="footer">
                         <div className="legend">
-                            <div><i className="fa fa-circle text-info" /> { this.props.data.labels[0] } </div>
-                            <div><i className="fa fa-circle text-warning" /> { this.props.data.labels[1] } </div>
-                            <div><i className="fa fa-circle text-danger" /> { this.props.data.labels[2] } </div>
+                            <div><i className="fa fa-circle text-info" /> { this.props.data.labels[0] } <Badge>{this.props.data.datasets[0].data[0]}</Badge></div>
```
Comment (iverberk) [inline frontend/src/components/charts/doughnut.js]: I think the extra badges are rather obtrusive and clutter the charts a bit too much (especially because they are not aligned). I'm even considering removing the legend altogether to clean things up. It seems to take up a lot of space while you can just hover/click the chart to find out what's what and choosing the right colors (green, orange, red) will mostly speak for themselves. What do you think?

File: frontend/src/router.js [hunk 11]
```diff
@@ -35,56 +35,60 @@ import Member from './containers/member';
...
-                <IndexRedirect to="/cluster" />
-                <Route path="/cluster" component={Cluster} />
 
-                <Route path="/members" component={Members} />
-                <Route path="/members/:memberId" component={Member}>
-                    <IndexRedirect to="/members/:memberId/info" />
-                    <Route path="/members/:memberId/info" component={MemberInfo} />
-                    <Route path="/members/:memberId/raw" component={MemberRaw} />
-                </Route>
+class AppRouter extends Component {
```
Comment (iverberk) [inline frontend/src/router.js]: Why did you change it to a component? A stateless function (like it was) will do the job?

File: frontend/src/sagas/event.js [hunk 12]
```diff
@@ -118,6 +113,13 @@ function* events() {
     }
 }
 
-export default function* eventSaga() {
-    yield fork(events)
+export default function eventSaga() {
+    return new Promise((resolve, reject) => {
+        const protocol = location.protocol === "https:" ? "wss:" : "ws:";
+        const url = `${protocol}//localhost:3000/ws`;
+        const p = connectTo(url);
```
Comment (iverberk) [inline frontend/src/sagas/event.js]: the p variable seems unnecessary. Just use connectTo(url).then ?

File: frontend/src/sagas/event.js [hunk 13]
```diff
@@ -102,14 +102,9 @@ function connectTo(url) {
...
 
-function* events() {
-    const protocol = location.protocol === "https:" ? "wss:" : "ws:";
-    const url = `${protocol}//${location.host}/ws`;
-
+function* events(socket) {
     while (true) {
         try {
-            console.log(`Connecting to backend: ${url}`)
-            const socket = yield call(connectTo, url)
```
Comment (iverberk) [inline frontend/src/sagas/event.js]: I understand why you moved the code but did you consider that it will not retry to connect to the backend on startup while it did that before?

File: frontend/src/store.js [hunk 14]
```diff
@@ -0,0 +1,41 @@
...
+        module.hot.accept('./reducers/root', () => {
+            const nextRootReducer = require('./reducers/root').default
+            store.replaceReducer(nextRootReducer)
+        })
+    }
+
+    store.runSaga = sagaMiddleware.run
+    store.close = () => store.dispatch(END)
+
+    return new Promise((resolve, reject) => {
```
Comment (iverberk) [inline frontend/src/store.js]: Nice!!

File: frontend/src/components/allocations.js [hunk 15]
```diff
@@ -0,0 +1,59 @@
+import React, { Component } from 'react';
+import { NomadLink } from './link';
+import DisplayTime from './time'
+import ReactTooltip from 'react-tooltip'
+
+class AllocationList extends Component {
```
Comment (jippi) [inline frontend/src/components/allocations.js]: I personally prefer explicit names, the file should have been `allocation_list` actually :)

File: frontend/src/components/evaluation/allocs.js [hunk 16]
```diff
@@ -1,6 +1,6 @@
 import React, { Component } from 'react';
 import { connect } from 'react-redux';
-import AllocationList from '../allocations'
+import AllocationList from '../allocation_list'
```
Comment (jippi) [inline frontend/src/components/evaluation/allocs.js]: best practice to have component and filename match, makes it much more predictable and easy to find what you are looking for as the project grow :)

File: frontend/src/components/job/allocs.js (hunk 9 above)
Comment (jippi) [inline frontend/src/components/job/allocs.js]: this is how React does this (tm) :) overriding Constructor is an antipattern

File: frontend/src/components/charts/doughnut.js (hunk 10 above)
Comment (jippi) [inline frontend/src/components/charts/doughnut.js]: for me the chart make no sense at all. if anything it should be a bar-chart with their legend+value below.. requireing me to use the mouse to get basic information is imo not good UX :)

File: frontend/src/router.js (hunk 11 above)
Comment (jippi) [inline frontend/src/router.js]: consistency :)

File: frontend/src/sagas/event.js (hunk 13 above)
Comment (jippi) [inline frontend/src/sagas/event.js]: no, thats an regression I need to find a fix for :)

File: frontend/src/sagas/event.js (hunk 12 above)
Comment (jippi) [inline frontend/src/sagas/event.js]: makes it easier to debug when things is not chained.. once it's proven stable it should be refactored into a more compact format for sure :)

File: frontend/src/sagas/event.js (hunk 13 above)
Comment (iverberk) [inline frontend/src/sagas/event.js]: Well, at this point the reloading is more important. We need to figure out how to deal with unavailable backend both during startup and in the middle of using the app. We'll figure it out later.

File: frontend/src/components/allocation/info.js [hunk 17]
```diff
@@ -23,6 +23,7 @@ class AllocInfo extends Component {
         let allocValues = {};
         allocProps.map((allocProp) => {
             allocValues[allocProp] = allocation[allocProp]
+            return null
```
Comment (jippi) [inline frontend/src/components/allocation/info.js]: `.map` expect a return, it just to shut up any IDE / linter for a warning :)

File: frontend/src/containers/cluster.js [hunk 18]
```diff
@@ -121,6 +121,7 @@ class Cluster extends Component {
 
         return (
             <div>
+                <Statistics />
```
Comment (jippi) [inline frontend/src/containers/cluster.js]: I agree to the overhaul - doughnuts are great on screenshot, but terrible for quick overview.. I'll try to come up with something more dense asap

File: frontend/src/components/time.js [hunk 19]
```diff
@@ -1,5 +1,6 @@
 import React, { Component } from 'react';
 import moment from 'moment'
+// this is actually used no matter what webpack says
```
Comment (jippi) [inline frontend/src/components/time.js]: it extends the `moment` object with additional formatting for duration

File: frontend/src/containers/jobs.js [hunk 20]
```diff
@@ -66,7 +78,7 @@ class Jobs extends Component {
                                 <tbody>
                                     {this.props.jobs.map((job) => {
                                         return (
-                                            <tr key={job.ID}>
+                                            <tr key={job.ID} className={this.jobStatusToColor(job.Status)}>
```
Comment (jippi) [inline frontend/src/containers/jobs.js]: I'm torn.. going to /jobs and not seeing anything non-green is a super fast way to get an overview.. though the pattern could be green (which we should expect is the biggest number of jobs) are no color, and other job states get colorized :)

**Comment by iverberk** [comment]
Awesome work! Thanks.
